### PR TITLE
[BUG][EasyWeather] issues resolved

### LINKED ISSUE #1: User needs to restart the app after granting location permission
## Issue Description
When the user installs the app for the first time and launches the app, the user is prompted with location access via a system dialog after the Splash Screen. After granting permission the app doesn't reload automatically to show the weather.

## Possible Fix
The Location access prompt should be during the Splash Screen instead of the home screen, which would make the app work perfectly. Now, when the home screen is painted it would be having the geolocator permission from previous step.

### LINKED ISSUE #2: Feels like is hidden on bigger fonts
WhatsApp Image 2020-04-28 at 3 48 17 AM

### LINKED ISSUE #3: Lock app in portrait orientation

### PR DESCRIPTION
**Pull request by virtualCobra**
I have worked upon the 3 listed issues.
1. Added a new UI button to get to your own location after the app start.
2. Potrait mode has been forced.
3. Pixel OverFlow by small dimension modification resolved.

-----
Fixes #1 #2 #3

### CODE REVIEW

**Comment by ShivamGoyal1899** [comment]
@virtualCobra Can you elaborate on the first point?

What I got is you have added a button that the user needs to tap the to get the weather, right?

**Review by shyvum — COMMENTED** [review]
@virtualCobra Can you elaborate on the first point?

What I got is you have added a button that the user needs to tap to get the weather, right?

**Comment by virtualCobra** [comment]
In the initial version of your app, it tries to access location on start. After adding UI button I have shifted startup setting to patiala and then could manually shift to current location. This ensures no issues during Starting of app


if the UI button feels nice to be in the layout I could work upon adding custom city(like by simply typing any city name)

**Comment by shyvum** [comment]
But why should the user even need to click on the button? What we see in most of the apps like Google weather itself, the location should be automatically fetched. I won't like an app where it shows me the weather of some other city, and I need to click on a button to get it corrected every time.

Also, about the search feature, it was initially in the version 2.0.0, I removed it keeping in mind the concept of the app was to make things easy and fast. The app is supposed to be an easy approach.

I've updated the issue with more details and steps to fix it correctly. See #1

**Comment by virtualCobra** [comment]
Okay I will see how to get that without that button

**Comment by shyvum** [comment]
@virtualCobra 
Just a follow-up, are you still working on the fix. As I'm thinking of patching it myself. Let me know whatever is the status.

**Comment by virtualCobra** [comment]
If you are on it then do it

**Comment by shyvum** [comment]
Thanks for contributing, @virtualCobra 
I've patched the bugs. Closing this issue now.

**Pull request closed without merging**
